// reportConfig.js
export const REPORT_TYPES = [
  { id: 'member_directory',          label: 'Member Directory',              icon: 'Users',         description: 'All members with mandal & kshetra' },
  { id: 'project_registrations',     label: 'Project Registrations',         icon: 'ClipboardList', description: 'Who registered for which project' },
  { id: 'attendance_by_member',      label: 'Attendance by Member',          icon: 'UserCheck',     description: 'Per-member attendance across projects' },
  { id: 'attendance_by_event',       label: 'Attendance by Event',           icon: 'Calendar',      description: 'Per-event present vs registered' },
  { id: 'project_member_attendance', label: 'Project × Member Attendance',   icon: 'BarChart2',     description: 'Select a project → member attendance %' },
  { id: 'mandal_summary',            label: 'Mandal Summary',                icon: 'MapPin',        description: 'Member & attendance stats per mandal' },
  { id: 'kshetra_summary',           label: 'Kshetra Summary',               icon: 'Map',           description: 'Stats rolled up per kshetra' },
  { id: 'inactive_members',          label: 'Inactive Members',              icon: 'UserX',         description: 'Members with zero registrations' },
];

export const REPORT_COLUMNS = {
  member_directory: [
    { key: 'internal_code', label: 'Member ID',   type: 'text'   },
    { key: 'name',          label: 'First Name',  type: 'text'   },
    { key: 'surname',       label: 'Last Name',   type: 'text'   },
    { key: 'father_name',   label: 'Father Name', type: 'text'   },
    { key: 'gender',        label: 'Gender',      type: 'text'   },
    { key: 'mobile',        label: 'Mobile',      type: 'text'   },
    { key: 'dob',           label: 'DOB',         type: 'date'   },
    { key: 'designation',   label: 'Designation', type: 'text'   },
    { key: 'mandal_name',   label: 'Mandal',      type: 'text'   },
    { key: 'kshetra_name',  label: 'Kshetra',     type: 'text'   },
    { key: 'address',       label: 'Address',     type: 'text'   },
    { key: 'is_guest',      label: 'Guest',       type: 'text'   },
    { key: 'created_at',    label: 'Joined',      type: 'date'   },
  ],
  project_registrations: [
    { key: 'member_code',   label: 'Member ID',    type: 'text'   },
    { key: 'member_name',   label: 'Member Name',  type: 'text'   },
    { key: 'gender',        label: 'Gender',       type: 'text'   },
    { key: 'mandal_name',   label: 'Mandal',       type: 'text'   },
    { key: 'kshetra_name',  label: 'Kshetra',      type: 'text'   },
    { key: 'project_name',  label: 'Project',      type: 'text'   },
    { key: 'exam_level',    label: 'Exam Level',   type: 'text'   },
    { key: 'seat_number',   label: 'Seat No',      type: 'text'   },
    { key: 'registered_at', label: 'Registered',   type: 'date'   },
  ],
  attendance_by_member: [
    { key: 'member_code',    label: 'Member ID',    type: 'text'   },
    { key: 'member_name',    label: 'Member Name',  type: 'text'   },
    { key: 'gender',         label: 'Gender',       type: 'text'   },
    { key: 'mandal_name',    label: 'Mandal',       type: 'text'   },
    { key: 'kshetra_name',   label: 'Kshetra',      type: 'text'   },
    { key: 'project_name',   label: 'Project',      type: 'text'   },
    { key: 'events_total',   label: 'Total Events', type: 'number' },
    { key: 'events_present', label: 'Present',      type: 'number' },
    { key: 'events_absent',  label: 'Absent',       type: 'number' },
    { key: 'attendance_pct', label: 'Attendance %', type: 'number' },
  ],
  attendance_by_event: [
    { key: 'project_name',   label: 'Project',      type: 'text'   },
    { key: 'event_name',     label: 'Event',        type: 'text'   },
    { key: 'event_date',     label: 'Date',         type: 'date'   },
    { key: 'registered',     label: 'Registered',   type: 'number' },
    { key: 'present',        label: 'Present',      type: 'number' },
    { key: 'absent',         label: 'Absent',       type: 'number' },
    { key: 'attendance_pct', label: 'Attendance %', type: 'number' },
  ],
  project_member_attendance: [
    { key: 'member_code',    label: 'Member ID',    type: 'text'   },
    { key: 'member_name',    label: 'Member Name',  type: 'text'   },
    { key: 'gender',         label: 'Gender',       type: 'text'   },
    { key: 'mandal_name',    label: 'Mandal',       type: 'text'   },
    { key: 'kshetra_name',   label: 'Kshetra',      type: 'text'   },
    { key: 'exam_level',     label: 'Exam Level',   type: 'text'   },
    { key: 'events_total',   label: 'Total Events', type: 'number' },
    { key: 'events_present', label: 'Present',      type: 'number' },
    { key: 'events_absent',  label: 'Absent',       type: 'number' },
    { key: 'attendance_pct', label: 'Attendance %', type: 'number' },
  ],
  mandal_summary: [
    { key: 'mandal_name',        label: 'Mandal',        type: 'text'   },
    { key: 'kshetra_name',       label: 'Kshetra',       type: 'text'   },
    { key: 'total_members',      label: 'Members',       type: 'number' },
    { key: 'yuvak_count',        label: 'Yuvaks',        type: 'number' },
    { key: 'yuvati_count',       label: 'Yuvatis',       type: 'number' },
    { key: 'total_registrations',label: 'Registrations', type: 'number' },
    { key: 'total_attendance',   label: 'Attendances',   type: 'number' },
  ],
  kshetra_summary: [
    { key: 'kshetra_name',       label: 'Kshetra',       type: 'text'   },
    { key: 'total_mandals',      label: 'Mandals',       type: 'number' },
    { key: 'total_members',      label: 'Members',       type: 'number' },
    { key: 'yuvak_count',        label: 'Yuvaks',        type: 'number' },
    { key: 'yuvati_count',       label: 'Yuvatis',       type: 'number' },
    { key: 'total_registrations',label: 'Registrations', type: 'number' },
    { key: 'total_attendance',   label: 'Attendances',   type: 'number' },
  ],
  inactive_members: [
    { key: 'internal_code', label: 'Member ID',   type: 'text' },
    { key: 'name',          label: 'First Name',  type: 'text' },
    { key: 'surname',       label: 'Last Name',   type: 'text' },
    { key: 'gender',        label: 'Gender',      type: 'text' },
    { key: 'mobile',        label: 'Mobile',      type: 'text' },
    { key: 'mandal_name',   label: 'Mandal',      type: 'text' },
    { key: 'kshetra_name',  label: 'Kshetra',     type: 'text' },
    { key: 'designation',   label: 'Designation', type: 'text' },
  ],
};

export const AGG_FUNCTIONS = [
  { value: 'none',  label: '—' },
  { value: 'count', label: 'COUNT' },
  { value: 'sum',   label: 'SUM' },
  { value: 'avg',   label: 'AVG' },
  { value: 'min',   label: 'MIN' },
  { value: 'max',   label: 'MAX' },
];

// All tables + columns for query autocomplete
export const DB_SCHEMA = {
  members:              ['id','internal_code','name','father_name','surname','gender','dob','mobile','address','designation','is_guest','mandal_id','created_at'],
  mandals:              ['id','name','kshetra_id','created_at'],
  kshetras:             ['id','name','created_at'],
  projects:             ['id','name','description','type','allowed_gender','is_active','registration_open','created_at'],
  events:               ['id','project_id','name','date','is_primary','created_at'],
  project_registrations:['project_id','member_id','exam_level','seat_number','registered_at'],
  attendance:           ['id','event_id','member_id','scanned_at'],
  tags:                 ['id','name','category','color'],
  user_profiles:        ['id','email','full_name','gender','role','assigned_kshetra_id','assigned_mandal_id'],
};